name: Validate

permissions: {}

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  validate:
    name: Validate
    uses: grafana/xk6/.github/workflows/extension-validate.yml@279c5f71399494d5c4f81aaddd536ae6b458d948 # v1.4.12
    permissions:
      pages: write
      id-token: write
      contents: read
    with:
      go-version: "1.26.x"
      go-versions: '["1.26.x"]'
      golangci-lint-version: "v2.13.2"
      platforms: '["ubuntu-latest", "windows-latest", "macos-latest"]'
      k6-versions: '["v2.2.0"]'
      xk6-version: "1.4.12"
      xk6-test-pattern: "test/*.test.{j,t}s"
